### ISSUE TITLE
White bar appearing at the top of the page.

### ISSUE THREAD

**Issue by rezlar** [rezlar/rezlar.github.io#12]
Gotta figure out how to move the photo up so everything is connected.

**Comment by turnervink** [comment]
![image 001](https://cloud.githubusercontent.com/assets/11531685/14233241/0cc69930-f978-11e5-9562-bc8c9d61ae81.png)

You've got a 10px bottom margin on the <ul> for the navbar. I'll try overriding it in the CSS.
