### ISSUE TITLE
Banner image doesn't display properly on large displays

### ISSUE THREAD

**Issue by turnervink** [rezlar/rezlar.github.io#9]
![image 001](https://cloud.githubusercontent.com/assets/11531685/13734632/30426b94-e95d-11e5-9acd-c0f65352a12b.png)

This is how the banner appears on my 1080p monitor.

**Comment by rezlar** [comment]
Yeah doesn't seem to be working on my monitor as well. Any suggestions?

**Comment by rezlar** [comment]
Fixed
